### ISSUE TITLE
Feature Request: Update Form Editor to New UI

### ISSUE THREAD

**Issue by jsdanie1** [onurmenal/crm-power-pane#139]
Would be nice if Form Editor Button would start navigating to the new Power App Editor.

**Comment by jsdanie1** [comment]
Does anybody read these? This has been opened for awhile. This plugin does still get updated right?

**Comment by mehmetseckin** [comment]
> Does anybody read these? This has been opened for awhile. This plugin does still get updated right?

Hi @jsdanie1, our apologies, we are aware of the issues/need for an update however we haven't been able to spare time to maintain the extension lately. In the meantime, any pull requests are more than welcome.

Closing this as I think #146 supersedes this issue -  it may be better to address this in a wider update updating various links across the extension.
