### ISSUE TITLE
Option to unhide Tabs and/or Sections

### ISSUE THREAD

**Issue by furqansafdar** [onurmenal/crm-power-pane#25]
It's not an issue rather a feature request that there should be an option to unhide tabs and/or sections to make them visible.

**Comment by onurmenal** [comment]
thanks Furqan,
i think we can manage it with Enable All Fields attirbute. I need to modifiy it for tabs and sections.

**Comment by onurmenal** [comment]
'Show Hidden Fields' action modified for tabs and section visibilities. It published on Chrome Store and it will be release after 60 minutes.  [4502e38](https://github.com/onurmenal/crm-power-pane/commit/6ca622ac9cf9def2e4181d35cbf1688c92637fc1)
