### ISSUE TITLE
Check out Level up

### ISSUE THREAD

**Issue by altmank** [onurmenal/crm-power-pane#28]
Sorry, not an issue but just wanted to share something similar to your project in case you didn't know it existed, it is similar:

@github\Levelup-for-Dynamics-CRM

**Comment by onurmenal** [comment]
thanks @altmank ,
There are many tools developed through bookmarks operation and There are many bookmarks that are common to CRM developers. Dynamics CRM Power Pane has its own unique features as well as providing common operations.
