### ISSUE TITLE
Fetch Xml

### ISSUE THREAD

**Issue by RafaelCavazza** [onurmenal/crm-power-pane#32]
Are there plans to implement some sort of FetchXml builder?

**Comment by onurmenal** [comment]
Hi @RafaelCavazza , 
Currently no, if you specify details for fetchxml builder that you think, maybe we can plan this for feature.
Also there is a fetchxml builder http://fxb.xrmtoolbox.com/ if you want to review it.
Thanks for your interest.

**Comment by RafaelCavazza** [comment]
Hello @onurmenal.

Sorry for the lack of response.
Actually what I wanted was to build / run FetchXml within CRM.
The Sonoma Plugin has this functionality and it helps us a lot.
But this plugin is exclusive to Chrome and we wanted an alternative that worked also in Mozilla.

Something like:
![image](https://user-images.githubusercontent.com/8078357/31740177-475e941c-b42f-11e7-96e6-50bf954e4410.png)

**Comment by onurmenal** [comment]
Hi @RafaelCavazza ,
Thanks for your feedback. It included to the plan. We will work on this as soon as possible.

**Comment by onurmenal** [comment]
Resolved with #96
