### ISSUE TITLE
Shortcut for open solution

### ISSUE THREAD

**Issue by AntoineGauthier** [onurmenal/crm-power-pane#37]
I would love if you could add a shortcut that would give us a dropdown of all the solutions available in the organization and allow us to open it.

**Comment by onurmenal** [comment]
Hi @AntoineGauthier 
thanks for your feedback. Your proposed feature is included in the plan.

**Comment by onurmenal** [comment]
Resolved with [#1cee342](https://github.com/onurmenal/crm-power-pane/commit/1cee342bef00f422b430620729e4b39ecc3ad7e5) version: 1.2.2
