### ISSUE TITLE
Show Hidden Fields should also show hidden sections and tabs

### ISSUE THREAD

**Issue by jasonroberts93** [onurmenal/crm-power-pane#39]

**Comment by onurmenal** [comment]
Hello @jasonroberts93 ,
We modified 'Show Hidden Fields' for showing hidden sections and tabs within #25  but that modification currently published only chrome store. I guess you are using Firefox addon. If it is so , we wil apply same changes to Firefox. Thanks for your feedback.

**Comment by jasonroberts93** [comment]
Hey Onur,

Yes you are correct I am using Firefox. Do you have an estimated time for release?

Thanks

Jason Roberts
Consultant | Business Solutions
Prosperity 24.7

E: jason.roberts@prosperity247.com
M: +44 (0) 7700 352274
T: +44 (0) 1534 877247
W: http://www.prosperity247.com

**Comment by onurmenal** [comment]
I am going to update it today. But release takes a few days. It could be relase tomorrow or next day.

**Comment by onurmenal** [comment]
Updated version publihed on Firefox store.

**Comment by jasonroberts93** [comment]
Wow that was quick! Good work Onur thanks for your hard work.

Jason Roberts
Consultant | Business Solutions
Prosperity 24.7

E: jason.roberts@prosperity247.com
M: +44 (0) 7700 352274
T: +44 (0) 1534 877247
W: http://www.prosperity247.com
