### ISSUE TITLE
Mobile Client feature not working

### ISSUE THREAD

**Issue by wikky2007** [onurmenal/crm-power-pane#57]
**Describe the bug**
I am trying to launch the Mobile Client functionality. When I click the Mobile Client button, it opens a second tab and a progress circle continuously spins, but the mobile version never loads. I have waited for about 5 minutes for it to load.

**To Reproduce**
1. Open Chrome with PowerPane extension installed.
2. Click the PowerPane thunderbolt in the upper left-hand corner to expand the menu.
3. Under Navigations, click the Mobile Client button.
4. An additional tab will open with the spinning progress circle.

**Expected behavior**
I would expect to see the usual preview and the "3/5" and/or "4/5" progress indicators (message like Downloading Customizations, etc.) in the bottom right-hand corner of the additionally opened tab.

**Screenshots**
![1](https://user-images.githubusercontent.com/43208878/45427413-d15c2400-b66c-11e8-92e7-acd506c1b06e.png)
![2](https://user-images.githubusercontent.com/43208878/45432273-78de5400-b677-11e8-94b8-48318d66dc85.png)

**Product Version**
 - Dynamics 365 v9 
 - Version:  9.0.2.1468

**Environment**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.92 (Official Build) (64-bit)

**Additional context**

**Comment by seckin92** [comment]
The URL hack [doesn't seem to be working](https://www.trellispoint.com/troubleshoot-dynamics-365-for-phones-using-browser/) on Dynamics 365 v9. This will need further research, but the feature might be dead :sob:

**Comment by seckin92** [comment]
Looks like this feature won't be available for Dynamics 365 v9. Thanks @wikky2007 for taking the time to write a detailed bug report. I will reopen this issue if we discover that it's possible to access the mobile client through the browser again.
