### ISSUE TITLE
Rename "Report Issue" button to "Provide Feedback"

### ISSUE THREAD

**Issue by seckin92** [onurmenal/crm-power-pane#60]
**Is your feature request related to a problem? Please describe.**
"Report Issue" implies bug reports, however users should be able to suggest features and give feedback.

**Describe the solution you'd like**
"Report Issue" button could be renamed to something like "Provide feedback" or "Tell us what you think" to cover bug reports, feature requests and general feedback. This button can open a new tab to the [new issue](https://github.com/onurmenal/crm-power-pane/issues/new/choose) page which lets the user _choose_ a suitable template for their feedback.

![Report-Issue.png](https://user-images.githubusercontent.com/1876867/47019708-9d828b80-d14f-11e8-8230-8554d498e31e.png)

**Describe alternatives you've considered**
Alternatively, other buttons for suggestions or general feedback can be added, but this might result in too much clutter / poor UX.

**Comment by ntjnh** [comment]
Happy to pick this up 😀
