### ISSUE TITLE
'npm run build-chrome' not working

### ISSUE THREAD

**Issue by HasanAliKaraca** [onurmenal/crm-power-pane#69]
**Describe the bug**
After cloning and running npm install. When i try to build the source i get the following error:

src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.

**Environment**
Windows 10

![image](https://user-images.githubusercontent.com/2185905/48253632-cc231780-e418-11e8-9fee-94bcb15b1959.png)

**Comment by HasanAliKaraca** [comment]
Hi, 
I deleted node_modules dir and package-lock.json in project directory. After using the commands, it worked.

npm cache clean --force
npm install

Versions:
node -v -> v10.10.0
npm -v -> 6.4.1
gulp not installed globally

**Comment by mehmetseckin** [comment]
I've updated the `package-lock.json` file, so this shouldn't be a problem anymore. Thanks for the heads up!
