### ISSUE TITLE
firefox+Unified interface compatibility 

### ISSUE THREAD

**Issue by popujol** [onurmenal/crm-power-pane#77]
Hello,
For Firefox, the button disappears in v9 Unified interface.
Do you plan to make it ocmpatible?
Thank you and best regards

**Comment by mehmetseckin** [comment]
Hi, thanks for your contribution. There is some work in progress in #81 regarding this issue, so marking this in-progress.

**Comment by mehmetseckin** [comment]
Resolved with #96, shipped in `1.2.0` (pending add-on store update).
