### ISSUE TITLE
Chrome; PowerPane not working in Unified Interface

### ISSUE THREAD

**Issue by Guustc** [onurmenal/crm-power-pane#78]
:bug: **Describe the bug**

The PowerPane add-on is not working with the new Unified Interface (https://docs.microsoft.com/nl-nl/dynamics365/customer-engagement/admin/about-unified-interface)

This is interface will be replacing the old one, so it would be great to have it working.

:clipboard: **To Reproduce**

Make a new model app for a specific Solution.
Set the mode on Unified Interface and add some entities
Open the app.

:thought_balloon: **Expected behavior**

Same behaviour as in the "classic" Dynamics 365 interface.

:zap: **Product Version**

 - Dynamics 365 v9 + Unified Interface APP.

**Comment by mehmetseckin** [comment]
Hi, thank you for your contribution. There is some work in progress in #81 regarding this issue, so marking this in-progress.

**Comment by mehmetseckin** [comment]
Resolved with #96, shipped in `1.2.0`
