### ISSUE TITLE
Build version for MS Edge (chromium based)

### ISSUE THREAD

**Issue by MichelSteen** [onurmenal/crm-power-pane#94]
:confused: The title is somewhat self explenatory. I really like this addon to all of my browsers. And i recently adopted the new Edge browser (chromium based) and i would love to have Power Pane in Edge

:bulb: Please build Power Pane for Edge ? 

:thought_balloon: Alternative solutions: I'm using GotDibbs which does work. But that's not PowerPane :)

:information_source: https://microsoftedge.microsoft.com/addons/

**Comment by mehmetseckin** [comment]
Thanks for the suggestion. We have created a port for EdgeHTML, but couldn't find time to port the extension for Edge Chromium just yet, but this is definitely something in our to-do list.

**Comment by mehmetseckin** [comment]
We added a port for Edge (Chromium). We will start the process of publishing the extension to the Edge store(s) after the Unified Interface port.

For now, you can download the Edge (Chromium) version from the [releases] (https://github.com/onurmenal/crm-power-pane/releases).

To install it, follow the [steps](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension#run-your-extension-locally-in-your-browser-while-developing-it-side-loading) on the official documentation, briefly:

1. Extract the `*.edge-chromium.zip` archive downloaded from the release.
2. Navigate to `edge://extensions`. 
3. Ensure Developer Mode is enabled (on the bottom left corner of the page).
4. Click the `Load Unpacked` button and select the folder you've extracted the extension.

![image](https://user-images.githubusercontent.com/1876867/72063982-d23dae00-32d2-11ea-9b2e-8b6c4766607c.png)
